Repository flutter/flutter-intellij, pull requests merged in 2019-05, with the labels that each got.

#3436 ui refactor of the settings dialog
  src/io/flutter/FlutterBundle.properties
  src/io/flutter/sdk/FlutterSettingsConfigurable.form
  src/io/flutter/sdk/FlutterSettingsConfigurable.java
  src/io/flutter/settings/FlutterSettings.java
Labels: cla: yes

#3433 update older todos
  src/io/flutter/FlutterBundle.properties
  src/io/flutter/FlutterUtils.java
  src/io/flutter/actions/InstallSdkAction.java
  src/io/flutter/module/settings/ProjectType.java
  src/io/flutter/preview/PreviewArea.java
  src/io/flutter/run/bazelTest/BazelTestFields.java
  src/io/flutter/run/common/TestLineMarkerContributor.java
Labels: cla: yes

#3438 Add an option to turn off closing labels in Dart source code when UI guides are on.
  src/io/flutter/editor/WidgetIndentsHighlightingPassFactory.java
  src/io/flutter/sdk/FlutterSettingsConfigurable.form
  src/io/flutter/sdk/FlutterSettingsConfigurable.java
  src/io/flutter/settings/FlutterSettings.java
Labels: cla: yes

#3441 Change log from 35.1 & plugin tool mod
  CHANGELOG.md
  resources/META-INF/plugin.xml
  tool/plugin/lib/plugin.dart
Labels: cla: yes

#3439 remove a no longer used 'PROJECTSYSTEM' case switch
  tool/plugin/lib/plugin.dart
Labels: cla: yes

#3445 Defensively ensure all offsets are within the document length before calling getLineNumber.
  src/io/flutter/editor/FliteredIndentsHighlightingPass.java
  src/io/flutter/editor/WidgetIndentsHighlightingPass.java
Labels: cla: yes

#3458 Restore source compatibility for the product matrix
  src/io/flutter/ProjectOpenActivity.java
  src/io/flutter/dart/FlutterDartAnalysisServer.java
Labels: cla: yes

#3459 Q2 survey notifcation
  src/io/flutter/FlutterInitializer.java
  src/io/flutter/FlutterMessages.java
  src/io/flutter/analytics/Analytics.java
  src/io/flutter/run/FlutterRunNotifications.java
  src/io/flutter/survey/FlutterSurveyNotifications.java
Labels: cla: yes

#3463 Update build for 2019.1.2 RC
  .travis.yml
  CHANGELOG.md
  product-matrix.json
  resources/META-INF/plugin.xml
  tool/plugin/test/plugin_test.dart
Labels: cla: yes

#3466 Support Android Studio beta 1
  .travis.yml
  CHANGELOG.md
  product-matrix.json
  resources/META-INF/plugin.xml
  tool/plugin/test/plugin_test.dart
Labels: P0, cla: yes, crash

#3470 Fix two bugs for widget guide outlines.
  src/io/flutter/editor/OutlineLocation.java
  src/io/flutter/editor/WidgetIndentGuideDescriptor.java
  src/io/flutter/editor/WidgetIndentsHighlightingPass.java
  src/io/flutter/editor/WidgetIndentsHighlightingPassFactory.java
Labels: cla: yes

#3472 Handle notifications when a project has been disposed more gracefully.
  src/io/flutter/editor/WidgetIndentsHighlightingPassFactory.java
Labels: cla: yes

#3469 fix an npe from the FlutterErrorReportSubmitter.java class
  src/io/flutter/FlutterErrorReportSubmitter.java
Labels: cla: yes

#3468 remove a println in WidgetIndentsHighlightingPass.java
  src/io/flutter/editor/WidgetIndentsHighlightingPass.java
Labels: cla: yes

#3481 remove the preview view from the flutter outline view
  src/io/flutter/FlutterBundle.properties
  src/io/flutter/dart/FlutterDartAnalysisServer.java
  src/io/flutter/dart/FlutterRequestUtilities.java
  src/io/flutter/preview/Handle.java
  src/io/flutter/preview/MoveHandle.java
  src/io/flutter/preview/PreviewArea.java
  src/io/flutter/preview/PreviewView.java
  src/io/flutter/preview/PreviewViewState.java
  src/io/flutter/preview/RenderHelper.java
  src/io/flutter/preview/RenderProblemKind.java
  src/io/flutter/preview/SelectionEditPolicy.java
  src/io/flutter/preview/SquareHandle.java
  src/io/flutter/preview/SquareHandlePosition.java
  src/io/flutter/preview/render_server_template.txt
  src/io/flutter/sdk/FlutterSearchableOptionContributor.java
  src/io/flutter/sdk/FlutterSettingsConfigurable.form
  src/io/flutter/sdk/FlutterSettingsConfigurable.java
  src/io/flutter/settings/FlutterSettings.java
Labels: cla: yes

#3487 Fix errors in AS 3.5 beta 1
  flutter-studio/src/io/flutter/actions/FlutterNewProjectAction.java
  flutter-studio/src/io/flutter/android/AndroidModuleLibraryManager.java
  flutter-studio/src/io/flutter/project/FlutterProjectStep.java
  flutter-studio/src/io/flutter/project/FlutterSettingsStep.form
  flutter-studio/src/io/flutter/project/FlutterSettingsStep.java
  resources/META-INF/studio-contribs.xml
  resources/META-INF/studio-contribs_template.xml
  tool/plugin/lib/plugin.dart
Labels: cla: yes

#3488 mark the device daemon process as a background process
  src/io/flutter/run/daemon/DeviceDaemon.java
Labels: cla: yes

#3490 limit the amount of time we wait for a graceful app shutdown
  src/io/flutter/run/daemon/FlutterApp.java
Labels: cla: yes

#3497 Remove the android studio specific memory view
  flutter-studio/src/io/flutter/profiler/FilterLibraryDialog.java
  flutter-studio/src/io/flutter/profiler/FlutterAllMemoryData.java
  flutter-studio/src/io/flutter/profiler/FlutterStage.java
  flutter-studio/src/io/flutter/profiler/FlutterStageView.java
  flutter-studio/src/io/flutter/profiler/FlutterStudioMonitorStage.java
  flutter-studio/src/io/flutter/profiler/FlutterStudioMonitorStageView.java
  flutter-studio/src/io/flutter/profiler/FlutterStudioProfilers.java
  flutter-studio/src/io/flutter/profiler/FlutterStudioProfilersView.java
  flutter-studio/src/io/flutter/profiler/GcDurationData.java
  flutter-studio/src/io/flutter/profiler/GcStatsDataSeries.java
  flutter-studio/src/io/flutter/profiler/Memory.java
  flutter-studio/src/io/flutter/profiler/ResetData.java
  flutter-studio/src/io/flutter/profiler/ResetStatsDataSeries.java
  flutter-studio/src/io/flutter/profiler/SnapshotData.java
  flutter-studio/src/io/flutter/profiler/SnapshotDataSeries.java
  src/io/flutter/devtools/DevToolsManager.java
  src/io/flutter/inspector/FrameRenderingDisplay.java
  src/io/flutter/inspector/HeapDisplay.java
  src/io/flutter/perf/EditorPerfDecorations.java
  src/io/flutter/server/vmService/VMServiceManager.java
  src/io/flutter/view/FlutterPerfView.java
  src/io/flutter/view/FlutterView.java
  src/io/flutter/view/InspectorMemoryTab.java
  src/io/flutter/view/InspectorPerfTab.java
  src/io/flutter/view/PerfFPSTab.java
  src/io/flutter/view/PerfMemoryTab.java
  src/io/flutter/view/PerfWidgetRebuildsTab.java
Labels: cla: yes

#3451 Introduce an opt-in detailed test runner for Bazel tests
  src/io/flutter/run/bazelTest/BazelTestFields.java
  src/io/flutter/run/bazelTest/BazelTestLaunchState.java
  src/io/flutter/run/common/ConsoleProps.java
  src/io/flutter/run/test/TestLaunchState.java
Labels: bazel, cla: yes

#3505 Make the save dialog refer to the save all action, not the save action
  src/io/flutter/sdk/FlutterSettingsConfigurable.form
Labels: cla: yes

#3510 Add quotes to the reload on save all tooltip
  src/io/flutter/sdk/FlutterSettingsConfigurable.form
Labels: cla: yes

#3507 Add an inline run menu option to run or watch Bazel Flutter tests
  resources/META-INF/plugin.xml
  resources/META-INF/plugin_template.xml
  src/io/flutter/run/bazelTest/BazelTestConfigProducer.java
  src/io/flutter/run/bazelTest/BazelTestFields.java
  src/io/flutter/run/bazelTest/BazelWatchTestConfigProducer.java
  src/io/flutter/run/bazelTest/FlutterBazelTestConfigurationType.java
  src/io/flutter/run/bazelTest/FlutterBazelTestLineMarkerContributor.java
  testSrc/unit/io/flutter/run/bazelTest/LaunchCommandsTest.java
Labels: bazel, cla: yes

#3513 Change DeviceDaemon to show a detailed error when it fails too many times.
  src/io/flutter/run/daemon/DeviceDaemon.java
Labels: cla: yes

#3524 guard against null project basedir
  src/io/flutter/editor/NativeEditorNotificationProvider.java
Labels: cla: yes

#3511 Enable devtools launching from Bazel
  src/io/flutter/bazel/PluginConfig.java
  src/io/flutter/bazel/Workspace.java
  src/io/flutter/devtools/DevToolsManager.java
  src/io/flutter/sdk/FlutterCommand.java
  src/io/flutter/sdk/FlutterSdk.java
  src/io/flutter/sdk/FlutterSdkVersion.java
  testSrc/unit/io/flutter/bazel/FakeWorkspaceFactory.java
  testSrc/unit/io/flutter/run/bazel/LaunchCommandsTest.java
  testSrc/unit/io/flutter/run/bazelTest/BazelTestConfigProducerTest.java
  testSrc/unit/io/flutter/run/bazelTest/LaunchCommandsTest.java
Labels: bazel, cla: yes

#3525 don't disable closing labels as part of UI Guides
  src/io/flutter/editor/WidgetIndentsHighlightingPassFactory.java
  src/io/flutter/sdk/FlutterSettingsConfigurable.form
  src/io/flutter/sdk/FlutterSettingsConfigurable.java
  src/io/flutter/settings/FlutterSettings.java
Labels: cla: yes

#3528 add in a preference to toggle closing labels
  src/io/flutter/sdk/FlutterSettingsConfigurable.form
  src/io/flutter/sdk/FlutterSettingsConfigurable.java
  src/io/flutter/settings/FlutterSettings.java
Labels: cla: yes

#3527 Update for new platform releases
  .gitignore
  .travis.yml
  product-matrix.json
  resources/META-INF/plugin.xml
  tool/plugin/lib/plugin.dart
  tool/plugin/test/plugin_test.dart
Labels: cla: yes

#3529 Gradle build
  .gitignore
  .idea/codeStyles/Project.xml
  build.gradle
  flutter-intellij.iml
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/io
  src/main/java/org
  src/main/resources
  testSrc/unit/io/flutter/testing/Testing.java
  tool/plugin/compile.xml
  tool/plugin/lib/plugin.dart
Labels: cla: yes

#3533 Update change log for M36
  CHANGELOG.md
  resources/META-INF/plugin.xml
Labels: cla: yes

#3534 tweak to the plugin.dart script
  tool/plugin/lib/plugin.dart
Labels: cla: yes

#3509 Configure default options for running Bazel
  src/io/flutter/dart/DartPlugin.java
  src/io/flutter/sdk/FlutterSettingsConfigurable.form
  src/io/flutter/sdk/FlutterSettingsConfigurable.java
  src/io/flutter/settings/FlutterSettings.java
Labels: cla: yes

#3520 remove survey notifications
  src/io/flutter/FlutterInitializer.java
  src/io/flutter/survey/FlutterSurveyNotifications.java
Labels: cla: yes

#3535 Sample Manager fixes.
  src/io/flutter/samples/FlutterSampleManager.java
Labels: cla: yes

#3536 query on a backgroundable task
  src/io/flutter/samples/FlutterSampleManager.java
Labels: cla: yes

#3539 Update for canary 2
  product-matrix.json
  tool/plugin/lib/plugin.dart
Labels: cla: yes

#3542 moar sample manager fixes
  src/io/flutter/samples/FlutterSampleManager.java
  src/io/flutter/sdk/FlutterSdk.java
Labels: cla: yes

#3545 Revert change to focus project in debugger
  src/io/flutter/server/vmService/DartVmServiceDebugProcess.java
Labels: cla: yes

#3546 task run synchronization
  src/io/flutter/samples/FlutterSampleManager.java
Labels: cla: yes

#3548 Resolve load conflict for beta
  product-matrix.json
Labels: cla: yes
